name: Deploy Quote App to Azure

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load .env file for Terraform & Docker
        run: |
          echo "Loading environment variables from .env"
          set -a
          source .env
          export ACR_NAME=$TF_VAR_acr_name
          export ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io
          export NODE_ENV=$NODE_ENV
          set +a

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies & build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Build and Push Docker Image
        run: |
          docker build \
            --build-arg NODE_ENV=$NODE_ENV \
            --build-arg DATABASE_URL=$DATABASE_URL \
            --build-arg REDIS_URL=$REDIS_URL \
            -t $ACR_LOGIN_SERVER/quoteapp:latest .
          docker push $ACR_LOGIN_SERVER/quoteapp:latest

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: $TF_VAR_webapp_name
          images: $ACR_LOGIN_SERVER/quoteapp:latest
